use mahi
create database upsc
create table UPSC_ESE(ST_NO BIGINT IDENTITY(201,1),ST_NAME VARCHAR(50),ST_MARKS INT,YOA INT)
INSERT INTO UPSC_ESE VALUES('MAHI',50,2000),('MAHA',60,2020),('MAHI',48,2019),('MAHA',58,2019),('MAHI',87,2017),('MAHI',79,2014)
SELECT*FROM UPSC_ESE
SELECT YOA,ST_MARKS,COUNT(*) AS NO_OF_ATTEMPTED_PEOPLES FROM UPSC_ESE GROUP BY YOA,ST_MARKS
SELECT COUNT(st_marks) FROM UPSC_ESE group by ST_MARKS
select count(*) from upsc_ese where st_marks>50

